In [1]:
import skimage.io as skio
import matplotlib.pyplot as plt
import numpy as np
from scipy import ndimage

C:\Users\tnemeth\Miniconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
UM_PER_PIXEL = 1.23

## Mean / SD Tortuosity

In [3]:
tort_filenames = [
    "H005/H005_tortuosity_data.csv",
    "H004/H004_tortuosity_data.csv",
    "H001/H001_OD_central_tortuosity_data.csv",
    "H001/H001_OS_tortuosity_data.csv"
]

# [mean tort, SD tort]
overall_tort_data = []

for fn in tort_filenames:
    this_data = np.loadtxt(fn, delimiter=",")
    overall_tort_data.append([np.mean(this_data[:,3]), np.std(this_data[:,3])])

overall_tort_data = np.asarray(overall_tort_data)

print("All Data: Mean, SD")
print(overall_tort_data)

#mean_of_means = 
print("\nMean of means: " + str(np.mean(overall_tort_data[:,0])))
print("SD of means: " + str(np.std(overall_tort_data[:,0])))

# T test to show difference from Alexopoulos numbers
#t_score = ()

All Data: Mean, SD
[[1.79371603 0.29460228]
 [2.25084955 0.44171288]
 [1.81484005 0.22633524]
 [2.0615261  0.105299  ]]

Mean of means: 1.9802329329348942
SD of means: 0.18840468087518963


## Perpendicular Pore Diameter Mean / SD

In [4]:
data_filenames = [
    "H005/H005_pore_diameter_data.csv",
    "H004/H004_pore_diameter_data.csv",
    "H001/H001_OD_central_pore_diameter_data.csv",
    "H001/H001_OS_pore_diameter_data.csv"
]

# [mean PPD, SD PPD]
overall_ppd_data = []

# Loop over each file
for fn in data_filenames:
    this_data = np.loadtxt(fn, delimiter=",")
    
    # Axial Scaling
    this_data[:,2] = this_data[:,2] * UM_PER_PIXEL
    
    # Remove outliers
    outlier_cutoff = np.percentile(this_data[:,2], 95)
    this_data = this_data[np.where(this_data[:,2] <= outlier_cutoff)]
    
    overall_ppd_data.append([np.mean(this_data[:,2]), np.std(this_data[:,2])])

overall_ppd_data = np.asarray(overall_ppd_data)

print("All Data: Mean, SD")
print(overall_ppd_data)

print("\nMean of means: " + str(np.mean(overall_ppd_data[:,0])))
print("SD of means: " + str(np.std(overall_ppd_data[:,0])))

All Data: Mean, SD
[[52.5466065  43.95310464]
 [28.18853119 28.07693185]
 [50.41964409 43.08917873]
 [48.5110483  40.1486545 ]]

Mean of means: 44.91645751919687
SD of means: 9.762797218620282


## Enface Pore Diameter Mean / SD

In [5]:
data_filenames = [
    "H005/H005_enface_radii_data.csv",
    "H004/H004_enface_radii_data.csv",
    "H001/H001_OD_central_enface_radii_data.csv",
    "H001/H001_OS_enface_radii_data.csv"
]

# [mean PPD, SD PPD]
overall_epd_data = []

# Loop over each file
for fn in data_filenames:
    this_data = np.loadtxt(fn, delimiter=",")
    
    # Axial Scaling
    this_data[:,2] = this_data[:,2] * UM_PER_PIXEL
    
    # Convert Radii to diameter
    this_data[:,2] = this_data[:,2] * 2
    
    overall_epd_data.append([np.mean(this_data[:,2]), np.std(this_data[:,2])])

overall_epd_data = np.asarray(overall_epd_data)

print("All Data: Mean, SD")
print(overall_epd_data)

print("\nMean of means: " + str(np.mean(overall_epd_data[:,0])))
print("SD of means: " + str(np.std(overall_epd_data[:,0])))

All Data: Mean, SD
[[47.77819616 20.23113757]
 [38.05378177 16.26817462]
 [48.40225516 16.09747629]
 [57.55674513 13.88285629]]

Mean of means: 47.94774455591608
SD of means: 6.900339091769839
